# Practice Problems from Algo Book

In [3]:
import numpy as np

## Q 6.1. Contiguous Subsequence

### Given subsequence [5,15,-30,10,-5,40,10] The answer of this 55 which comes from 10+-5+40+10

In [125]:
def contiguous_subsequence(list1):
    seqlen = len(list1)
    L = np.zeros(seqlen)
    
    L[0] = list1[0]
    maxval = L[0]
    for j in range(1,seqlen,1):
        aj = list1[j]
        L[j]= max(aj,aj+L[j-1])
        if L[j] > maxval:
            maxval = L[j]
    return maxval      

In [126]:
list1 = [5,15,-30,10,-5,40,10]
print(contiguous_subsequence(list1))

55.0


## Q 6.2. Hotel sequence

In [127]:
list1 = np.random.randint(0,150,15)

In [128]:
list2 = []
for i in range(len(list1)+1):
    list2.append(np.sum(list1[:i]))

In [129]:
print(list2)

[0, 76, 219, 323, 438, 583, 683, 761, 875, 964, 1059, 1098, 1192, 1197, 1222, 1269]


## Q 6.4. Corrupted Text 

In [130]:
def reconstruct(string,dict1):
    output = ""
    for i in range(len(string)):
        for j in range(i):
            word = string[j:i+1]
            if word in dict1:
                output = output + word + " "
    return output

In [131]:
string = "itwasthebestoftimes..."
dict1 = ["it", "was", "the", "best", "of", "times", "."]

In [132]:
print(reconstruct(string,dict1))

it was the best of times 


## Knapsack Problem (Lectures)

In [133]:
def knapsack(weights, values, B):
    n = len(values)
    K = np.zeros((n,B+1))
    for i in range(1,n,1):
        for b in range(0,B+1,1):
            if weights[i]<= b:
                K[i,b] = max(K[i-1,b-weights[i]] + values[i], K[i-1,b])
            else:
                K[i,b] = K[i-1,b]
    print(K)
    return K[n-1,-1]

In [134]:
weights = [15,12,10,5]
values = [15,10,8,1]
B = 22
print(knapsack(weights, values, B))

[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0. 10. 10. 10. 10. 10. 10.
  10. 10. 10. 10. 10.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  8.  8. 10. 10. 10. 10. 10. 10.
  10. 10. 10. 10. 18.]
 [ 0.  0.  0.  0.  0.  1.  1.  1.  1.  1.  8.  8. 10. 10. 10. 10. 10. 11.
  11. 11. 11. 11. 18.]]
18.0


## Q.6.7) Longest Palindrome Subsequence

### Explanation to the solution can be found here: https://youtu.be/TLaGwTnd3HY 
#### - credits https://www.geeksforgeeks.org/longest-palindromic-subsequence-dp-12/

In [135]:
def longest_palindrome_subsequenece(seq):
    n = len(seq)
    L = np.zeros((n,n))
    for i in range(n):
        L[i][i] = 1
    for sl in range(2,n+1,1):
        for i in range(0,n-sl+1):
            j = i + sl -1
            if seq[i] == seq[j]:
                L[i,j] = L[i+1,j-1] + 2
            else:
                L[i,j] = max(L[i+1,j],L[i,j-1])
    #print(L)
    return L[0,n-1]

In [136]:
seq = "BABCBAB"
seq = "ACGTGTCAAAATCG"
print(longest_palindrome_subsequenece(seq))

8.0


## Q.6.17) Denomination for value V

In [137]:
def tender_change(deno, value):
    n = len(deno)
    K = np.zeros(value+1)
    #print(n)
    for g in range(1,value+1,1):
        for i in range(len(deno)):
            #print(i)
            if g >= deno[i] and K[g]!=value:
                K[g] = K[g-deno[i]] + deno[i]
    #print(K)
    if K[-1] == value:
        return True
    else:
        return False
    
    

In [138]:
deno = [3,5,2]
value = 13
print(tender_change(deno, value))

True


## Q.6.18) Denomination for value V (use denomination at most once)

In [139]:
def tender_change1(deno, value):
    n = len(deno)
    K = np.zeros((n,value+1))
    #print(n)
    for i in range(0,n,1):
        for g in range(1,value+1,1):
        
            #print(i)
            if g >= deno[i] and K[i,g]!=value:
                K[i,g] = K[i-1,g-deno[i]] + deno[i]
            else:
                K[i,g] = K[i-1,g]
    #print(K)
    if K[-1,-1] == value:
        return True
    else:
        return False

In [140]:
deno = [1,5,10,20]
value = 40
print(tender_change1(deno, value))

False


## Q.6.19) Denomination for value V (Minimum coins to tender a change)

In [250]:
def tender_change2(deno, value,count):
    n = len(deno)
    #K = np.zeros((n,value+1))
    K = np.zeros(value+1)
    #K = K * np.float("inf")
    #print(n)
    K[0]  = 0
    print(np.linspace(0,15,16))
    for i in range(1,value+1,1):
        K[i] = np.float("inf")
        for j in range(0,n,1):
            if deno[j]<=i:
                #print("here")
                sub_res = K[i-deno[j]]
                if (sub_res != np.float("inf")): 
                    K[i] = min(K[i],sub_res + 1)
                
                
    print(K)
    return K[-1]


In [253]:
deno = [1,5,10,20]
value = 15
count = 4
print(tender_change2(deno, value,count))

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15.]
[0. 1. 2. 3. 4. 1. 2. 3. 4. 5. 1. 2. 3. 4. 5. 2.]
2.0


## Q.6.20 Optimal Binary Search Tree

In [291]:
def sum1(freq, i, j): 
    s = 0
    for k in range(i, j+1): 
        s += freq[k]  
    return s  

def optimal_tree(keys, freq):
    n = len(keys)
    #print(n)
    cost = np.ones((n,n))
    cost = cost * np.float("inf")
    for i in range(n):
        cost[i,i] = freq[i]
    for L in range(2,n+1):
        for i in range(n+2-L):
            j = i + L -1
            #print(j)
            if i >=n or j >= n:
                break
            for r in range(i,j+1):
                c = 0
                if keys[r] > keys[i]:
                    c += cost[i,r-1]
                elif keys[j]>keys[r]:
                    c += cost[r+1,j]
                    
                c += sum1(freq,i,j)
                cost[i,j] = min(cost[i,j],c)
    print(cost)
    return cost[0][n - 1]     
    

In [292]:
keywords = ['begin','do','else','end','if','then','while']
frequency = [0.05,0.40,0.08,0.04,0.10,0.10,0.23]
print(optimal_tree(keywords, frequency))

[[0.05 0.5  0.58 0.62 0.72 0.82 1.05]
 [ inf 0.4  0.56 0.68 0.92 1.12 1.35]
 [ inf  inf 0.08 0.16 0.3  0.4  0.63]
 [ inf  inf  inf 0.04 0.18 0.28 0.51]
 [ inf  inf  inf  inf 0.1  0.3  0.53]
 [ inf  inf  inf  inf  inf 0.1  0.43]
 [ inf  inf  inf  inf  inf  inf 0.23]]
1.05


## Q 6.15 Probability of A winning n games

In [17]:
def proba(n,a,b):
    Pa = 0.5
    Pb = 1.0-Pa
    P = np.zeros((n,n))
    for i in range(0,n):
        P[i,n-1] = Pa**(n-i)
    #print(P)
    for i in range(n-1,-1,-1):
        for j in range(n-2,-1,-1):
            P[i,j] = P[i,j+1] + ((Pa **(n-i)) * (Pb**(n-1-j)) )
    #print(P)
    return P[a,b]

In [19]:
n = 8
a = 7
b = 5
print(proba(n,a,b))

0.875


## DP HW - Problem 1: Longest Sub*!?*

In [5]:
X = "abdbabfgd"
Y = "betfdbfafr"

In [30]:
def subseqstr(X,Y):
    m = len(X)
    n = len(Y)
    #T = np.zeros((m,n))
    T = np.zeros(m+1)
    
    for j in range(n):
        if X[0] == Y[j]:
            T[0] =1
    tempj = -1
    maxval = 0
    for i in range(1,m):
        for j in range(0,n):
            if X[i] == Y[j]:
                T[i] = 1
                for k in range(j):
                    if X[i-1] == Y[k]:
                        T[i] = T[i-1] + 1
                        tempj = j
        maxval = max(maxval,T[i])
                    
    print(T)
    return maxval

In [87]:
def subseqstr1(X,Y):
    m = len(X)
    n = len(Y)
    T = np.zeros((m+1,n+1))
    #T = np.zeros(m+1)
    
    
    #print(T)
        
    tempj = 0
    maxval = 0
    for i in range(1,m+1):
        for j in range(1,n+1):
            T[i,j] = T[i,j-1]
            if X[i-1] == Y[j-1]:
                T[i,j] = max(T[i-1,j-1] + 1,T[i,j])
            
            maxval = max(maxval,T[i,j])
                    
    print(T)
    return maxval

In [88]:
X = "abdbabfgd"
Y = "betfdbfafr"
print(subseqstr1(X,Y))

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0. 2. 2. 2. 2. 2. 2.]
 [0. 1. 1. 1. 1. 1. 3. 3. 3. 3. 3.]
 [0. 0. 0. 0. 0. 0. 0. 0. 4. 4. 4.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 2. 2. 2. 2. 2. 2. 2.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 1. 1. 1. 1. 1.]]
4.0


In [84]:
Y = "ABCD"
X = "BACDBDCD"
print(subseqstr1(X,Y))

[[0. 0. 0. 0.]
 [0. 1. 1. 1.]
 [0. 1. 1. 2.]
 [0. 1. 1. 2.]]
2.0


In [107]:
def subseqstr2(X,Y):
    m = len(X)
    n = len(Y)
    #T = np.zeros((m,n))
    T = np.zeros(m+1)
    
    for j in range(n):
        if X[0] == Y[j]:
            T[0] =1
    tempj = -1
    maxval = T[0]
    for i in range(1,m):
        for j in range(0,n):
            if X[i] == Y[j] :
                T[i] = 1
                if tempj == -1:
                    tempj = j
                elif X[i-1] == Y[tempj] and j>tempj:
                    T[i] = T[i-1] + 1
                    tempj = j
            #print(tempj)
        maxval = max(maxval,T[i])
                    
    print(T)
    return maxval

In [111]:
X = "abdbabfgd"
Y = "betfdbfafr"
print(subseqstr2(X,Y))

[1. 1. 2. 3. 4. 1. 1. 0. 1. 0.]
4.0


In [112]:
Y = "ABCD"
X = "BACDBDCD"
print(subseqstr2(X,Y))

[1. 1. 2. 3. 1. 1. 1. 1. 0.]
3.0


## Q 6.22 Subsets of a list sum to t

In [45]:
def sumto_n(list1, n):
    T = np.zeros(n+2)
    #i_list = []
    for i in range(1,n+2,1):
        #i_list.append(i)
        for ele in list1:
            if ele <= i:
                if i - ele != ele:
                    T[i] = ele + T[i-ele]
                    
                    if i != T[i]:
                        T[i] = 0
    #print(i_list)                
    print(T)
    return T[n]
    

In [47]:
list1 = [3,5,8]
n = 17
print(sumto_n(list1, n))

[ 0.  0.  0.  3.  0.  5.  0.  0.  8.  0.  0. 11.  0. 13.  0.  0. 16.  0.
  0.]
0.0
